# Generated by Django 5.1.13 on 2025-10-10 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('es_opcional', models.BooleanField(default=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.hotel')),
                ('servicios', models.ManyToManyField(blank=True, related_name='habitaciones', to='hotel.servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hotel.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilHuesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=50)),
                ('numero_pasaporte', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('puntos_fidelidad', models.IntegerField(default=0)),
                ('preferencias', models.TextField(blank=True)),
                ('huesped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='hotel.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('F', 'Finalizada'), ('X', 'Cancelada')], default='P', max_length=1)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='hotel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_en_momento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='reservas', through='hotel.ReservaServicio', to='hotel.servicio'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='hoteles', to='hotel.servicio'),
        ),
    ]
