# Generated by Django 5.1.14 on 2025-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_correo_contacto_hotel_hora_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
    ]
