# Generated by Django 5.1.14 on 2025-12-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_habitacion_imagen_url_habitacion_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
