# Generated by Django 5.1.14 on 2025-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hoteles/'),
        ),
    ]
