# Generated by Django 5.1.14 on 2025-12-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_delete_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='ReservaServicio',
        ),
    ]
