# Generated by Django 5.1.14 on 2025-12-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='imagen',
        ),
    ]
