# Generated by Django 5.1.14 on 2025-12-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_reservaservicio_reserva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilHuesped',
        ),
    ]
