# Generated by Django 5.1.14 on 2025-12-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_delete_perfilhuesped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactoHotel',
        ),
    ]
