# Generated by Django 5.1.14 on 2025-12-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_delete_contactohotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
